# Custom Language File for Launcher Customizer

[ejs.app]
title = "SMC Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Xeravax/SMC-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/Xeravax/SMC-Launcher"
supportLink = "https://github.com/Xeravax/SMC-Launcher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO THE SHIELD MODPACK"
welcomeDescription = "You’ve landed in the right place. This is the official SHIELD modpack—built for the staff and allies of SHIELD, so you get a tailored experience from the ground up. We’ve packed it with a ton of mods so you can jump straight into the action without the usual setup hassle. Everything runs through this custom launcher: one click, and you’re in. Custom launcher go bbbrts."
welcomeDescCTA = "Hit launch and enjoy—you’re a few clicks away from the full SHIELD experience."
